#!/usr/bin/env bash

global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	deamon

defaults
    log     global
    mode    http
    option  httplog
	timeout connect  5000
	timeout client  5000
	timeout server  5000

frontend ft_www
	bind *:80
	bind *:443 ssl crt /etc/haproxy/certs/www.holberton.online.pem
	http-request redirect scheme https unless { ssl_fc }
	http-request set-header X-Forwarded-Proto https
	mode tcp
	default_backend kb_www

backend bk_www
	mode tcp
	balance roundrobin
	server 176572-web-01 34.207.227.106:80 check
	server 176572-web-02 54.146.87.2:80 check
